### PR TITLE
First draft FR#33

### PR DESCRIPTION
**Pull request by mosen**
computercommand has a totally different representation in the request and response.
I was quite confused about the use of data_keys in that case. 

The most similar resources i could find to the command API were logflush and commandflush. Neither of those seemed to use save(), so in the same spirit i added the send() method for creating a single command.

Do not accept! just for review.

### CODE REVIEW

**Comment by sheagcraig** [comment]
@mosen-this is great. Thanks for implementing this. There's no way I would be able to do this on my own right now!

Does it work?

**Comment by sheagcraig** [comment]
It seems to me like the API documentation is saying you have three ways to POST a new command:
1. POST with url API_BASE/computercommands/command/[DeviceLock|BlankPush|PasscodeLock|UnmanageDevice] with data = XML that contains the name of the command, the computers it should apply to, and for EraseDevice and DeviceLock a passcode.
2. POST with url API_ASE/computercommands/command/[BlankPush|UnmanageDevice]/id/[one or more ids, comma separated] with data = XML that contains the name.
3. POST with url API_ASE/computercommands/command/[PasscodeLock|DeviceLock]/passcode/[passcode]/id/[one or more ids, comma separated] with data = XML that contains the name.

It seems silly to support all three methods. I feel like these are available as a convenience for developers who just want to pick one. I suggest that we use the first method, and make easy properties on the ComputerCommand object to manage the variables:
1. CommandType
2. Computers to apply it to
3. Passcode

I believe there's already code in place to take a `jss.Computer` object and add it to other objects, like `ComputerGroup`, which gets a stripped-down representation of the object to add as a subelement to the container element. This could be used here for the `<computer_command><computers>` container, which would be consistent with the API. The same method could also accept int input which would be assumed to be a computer ID, and probably str/unicode, which would probably need to get converted to an ID behind-the-scenes (e.g. `self.jss.Computer(str_name_argument).id`.

What do you think about the `save` vs. `send` method for actually performing the POST? I think that my understanding of how these work is that when you create the command, it immediately sends it to the computers listed, and that there's no way to create a command (actually on the JSS) without having it immediately apply. I think that just overriding the `save` method would be acceptable here.

Annoyingly, I see that there are more command types than are supported through the API (ProfileList, CertificateList for example).

**Comment by sheagcraig** [comment]
I can get this in before the next big release if @mosen can vouch for it working correctly!

**Comment by mosen** [comment]
haven't reviewed it in some time, i will check against 9.101.

**Comment by sheagcraig** [comment]
@mosen let's test this up and get it in!

**Pull request merged**
