### PR TITLE
Feature/docs

### PR DESCRIPTION
**Pull request by mosen**
Created sphinx-quickstart configuration in doc/
Automatically generated and tested with readthedocs.org. coverage of classes is still spotty.
Converted entire wiki to ReST for RTD.

Preview available here: http://mopython-jss.readthedocs.io/en/latest/

### CODE REVIEW

**Comment by sheagcraig** [comment]
This looks awesome @mosen. I'll be looking at this soon.

**Comment by sheagcraig** [comment]
Merged into testing. I'll have to work on a bunch of stuff to get it up to snuff, especially with all of the changes, but this looks great. Thanks!

**Comment by sheagcraig** [comment]
What do you think about this these days @mosen? Merge it in and move on from there?

**Comment by mosen** [comment]
There are no conflicts and no code changes here. If the docs have become out of date(ish) I'll do up another PR. Please merge

**Pull request merged**
